package Catal::Model::CatalDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Catal::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:cataldb',
        user => 'cataluser',
        password => 'catalpass',
        AutoCommit => q{1},
        on_connect_do => ["SET NAMES utf8"],
    }
);

=head1 NAME

Catal::Model::CatalDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Catal>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Catal::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.41

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
